-- MOVIDO / OBSOLETO
-- La versión canónica de esta migración vive en:
--   farmacia-sync/sql/migracion-fefo-lotes.sql
--
-- Este archivo quedó obsoleto al consolidar dos variantes divergentes del
-- esquema de lotes (sku+lote vs producto_id+codigo) creadas en sesiones
-- distintas. Ejecuta la canónica; no borres este stub (evita que el nombre
-- vuelva a atraer a la variante vieja).
